const blueprints=[
 {id:'bolt-01',name:'Bolt-01',category:'Robot',desc:'Compact beginner-friendly paper robot.',difficulty:'Beginner',time:'30–45 min',art:'bolt'},
 {id:'nova',name:'Nova',category:'Hero',desc:'A futuristic original hero designed specifically for paper construction.',difficulty:'Intermediate',time:'45–60 min',art:'nova'},
 {id:'ember',name:'Ember',category:'Fantasy',desc:'A small fantasy guardian with a bold silhouette.',difficulty:'Intermediate',time:'45–60 min',art:'ember'},
 {id:'atlas-mk2',name:'Atlas-MK2',category:'Robot',desc:'A larger mech-style paper figure for experienced builders.',difficulty:'Advanced',time:'60–90 min',art:'atlas'},
];
const grid=document.querySelector('#blueprint-grid'),search=document.querySelector('#search'),empty=document.querySelector('.empty');let active='all';
function card(b){return `<article class="bp-card" data-id="${b.id}"><button class="bp-art ${b.art}" aria-label="View ${b.name} blueprint details"><span>PF-${b.id.toUpperCase()}</span><i class="figure-shape"></i></button><div class="card-content"><span class="category">${b.category}</span><h3>${b.name}</h3><p>${b.desc}</p><div class="meta"><span>${b.difficulty}</span><span>${b.time}</span></div><button class="button ghost download" data-download="${b.id}">Download PDF ↓</button></div></article>`}
function render(){const term=search.value.toLowerCase();const shown=blueprints.filter(b=>{const filter=active==='all'||b.category.toLowerCase()===active||(active==='beginner'&&b.difficulty==='Beginner');return filter&&(b.name.toLowerCase().includes(term)||b.category.toLowerCase().includes(term))});grid.innerHTML=shown.map(card).join('');empty.hidden=!!shown.length}render();
search.addEventListener('input',render);document.querySelectorAll('.filter').forEach(x=>x.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');x.classList.add('active');active=x.dataset.filter;render()}));
const modal=document.querySelector('#detail-modal'),modalContent=document.querySelector('#modal-content');
grid.addEventListener('click',e=>{const card=e.target.closest('.bp-card');if(!card)return;const b=blueprints.find(x=>x.id===card.dataset.id);if(e.target.closest('[data-download]')){toast('Blueprint coming soon. Check back shortly!');return}modalContent.innerHTML=`<div class="modal-layout"><div class="bp-art ${b.art}"><span>PF-${b.id.toUpperCase()}</span><i class="figure-shape"></i></div><div><span class="category">${b.category}</span><h2>${b.name}</h2><p class="lede">${b.desc}</p><div class="meta"><span>${b.difficulty}</span><span>${b.time}</span></div><div class="button-row"><button class="button primary" data-modal-download>Download PDF</button><button class="button ghost" data-toast="Instructions will be added with the final blueprint.">View Instructions</button><button class="button ghost" data-share>Share</button></div><h3>What you'll need</h3><div class="need-list"><span>• A4 paper</span><span>• Printer</span><span>• Scissors</span><span>• Glue</span><span>• Ruler</span><span>• Optional coloring tools</span></div><h3>Build Preview</h3><div class="build-preview"><span>1. PRINT</span><span>2. CUT</span><span>3. FOLD</span><span>4. BUILD</span></div><p class="safety">Always follow safe crafting practices when using scissors or other tools.</p></div></div>`;modal.showModal()});
document.querySelector('.modal-close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});modalContent.addEventListener('click',e=>{if(e.target.matches('[data-modal-download]'))toast('Blueprint coming soon. Check back shortly!');if(e.target.matches('[data-share]')){navigator.clipboard?.writeText(location.href);toast('Link copied to clipboard!')}if(e.target.dataset.toast)toast(e.target.dataset.toast)});
const toastEl=document.querySelector('.toast');let timer;function toast(message){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toastEl.classList.remove('show'),3000)}document.querySelectorAll('[data-toast]').forEach(x=>x.onclick=()=>toast(x.dataset.toast));
document.querySelector('#signup-form').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('.form-message').textContent='You’re on the forge list — welcome aboard!';e.currentTarget.reset()});
const nav=document.querySelector('nav'),toggle=document.querySelector('.menu-toggle');toggle.onclick=()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation')};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const observer=new IntersectionObserver(items=>items.forEach(i=>{if(i.isIntersecting){i.target.classList.add('visible');observer.unobserve(i.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
